#!/bin/sh

export LANG=en_GB.UTF-8
export LC_ALL=en_GB.UTF-8

mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys

mkdir -p /sys/fs/cgroup
mount -t cgroup2 cgroup2 /sys/fs/cgroup

mount -t tmpfs tmpfs /run
mount -t tmpfs tmpfs /tmp

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

exec /lib/systemd/systemd
