name: Build Hook Appliance

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'overlay/**'
      - '.github/workflows/**'

env:
  HOOK_VERSION: v0.11.1

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        arch:
          - hook-default-amd64
          - hook-default-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache LinuxKit
        uses: actions/cache@v4
        with:
          path: |
            hook/cache
          key: linuxkit-${{ runner.os }}-${{ matrix.arch }}
      - name: Restore prebuilt kernel cache
        uses: actions/cache@v4
        with:
          path: |
            /tmp/hook-kernel-cache
          key: hook-kernel-${{ matrix.arch }}-${{ env.HOOK_VERSION }}
      - name: Clone Hook
        run: |
          git clone --depth=1 --branch ${HOOK_VERSION} https://github.com/tinkerbell/hook.git
      - name: Restore cached kernel image
        run: |
          mkdir -p /tmp/hook-kernel-cache
          if [ -f /tmp/hook-kernel-cache/kernel.tar ]; then
            docker load < /tmp/hook-kernel-cache/kernel.tar
          else
            echo "No cached kernel image found"
          fi
      - name: Build kernel if needed
        run: |
          cd hook
          if docker image inspect quay.io/tinkerbell/hook-kernel:5.10.255-70151c3e >/dev/null 2>&1; then
            echo "Kernel already cached"
          else
            echo "Building kernel"
            ./build.sh kernel ${{ matrix.arch }}
            mkdir -p /tmp/hook-kernel-cache
            docker save quay.io/tinkerbell/hook-kernel:5.10.255-70151c3e > /tmp/hook-kernel-cache/kernel.tar
          fi

      - name: Save kernel cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            /tmp/hook-kernel-cache
          key: hook-kernel-${{ matrix.arch }}-${{ env.HOOK_VERSION }}

      - name: Copy overlay files
        run: |
          mkdir -p hook/files/etc/profile.d
          mkdir -p hook/files/etc/init.d

          cp overlay/local.sh hook/files/etc/profile.d/local.sh
          cp overlay/002-banner.sh hook/files/etc/init.d/002-banner.sh

      - name: Build Hook appliance
        run: |
          cd hook
          ./build.sh build ${{ matrix.arch }}

      - name: Show outputs
        run: |
          find hook/out -type f

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hook-${{ matrix.arch }}
          path: |
            hook/out/linuxkit-${{ matrix.arch }}/hook-kernel
            hook/out/linuxkit-${{ matrix.arch }}/hook-initrd.img
            hook/out/linuxkit-${{ matrix.arch }}/hook-cmdline
